version: '1'
services:
  api:
    image: nowports-test
    build: .
    networks:
      - backend
    ports:
      - "3015:3015"

  web-cli:
    image: nowports-test
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge
